name: Ratchet coverage
description: Run cargo llvm-cov and fail if coverage decreases
inputs:
  baseline-file:
    description: Path to store the coverage baseline
    required: false
    default: .coverage-baseline
  args:
    description: Additional arguments passed to cargo llvm-cov
    required: false
    default: ''
outputs:
  percent:
    description: Coverage percentage reported by cargo llvm-cov
    value: ${{ steps.cov.outputs.percent }}
runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        uv-version: ">=0.7.19,<0.8.0"
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
          **/scripts/*.py
    - name: Restore baseline
      uses: actions/cache@v4
      with:
        path: ${{ inputs.baseline-file }}
        key: ratchet-baseline-${{ runner.os }}
    - name: Cache cargo artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-llvm-cov
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-llvmcov-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-llvmcov-
    - name: Install cargo-llvm-cov
      run: uv run --script "${{ github.action_path }}/scripts/install_cargo_llvm_cov.py"
      shell: bash
    - if: runner.os == 'Windows'
      name: Install bc (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        install: bc
        path-type: inherit
    - name: Run coverage
      id: cov
      run: uv run --script "${{ github.action_path }}/scripts/run_coverage.py" --args "${{ inputs.args }}"
      shell: bash
    - name: Ratchet coverage
      run: |
        uv run --script "${{ github.action_path }}/scripts/ratchet_coverage.py" \
          --baseline-file "${{ inputs.baseline-file }}" \
          --current "${{ steps.cov.outputs.percent }}"
      shell: bash
    - name: Save baseline
      if: success()
      uses: actions/cache@v4
      with:
        path: ${{ inputs.baseline-file }}
        key: ratchet-baseline-${{ runner.os }}
