name: Setup Rust
description: Install Rust and cache cargo registry
inputs:
  install-postgres-deps:
    description: Install PostgreSQL system dependencies
    required: false
    default: false
  install-sqlite-deps:
    description: Install SQLite development libraries on Windows
    required: false
    default: false
  use-sccache:
    description: Enable sccache for non-release runs
    required: false
    default: "true"
  sccache-action-version:
    description: Version tag for mozilla-actions/sccache-action
    required: false
    default: "v0.0.10"
runs:
  using: composite
  steps:
    - name: Install rust
      uses: actions-rust-lang/setup-rust-toolchain@9d7e65c320fdb52dcd45ffaa68deb6c02c8754d9
      with:
        override: true
        components: rustfmt, clippy, llvm-tools-preview
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/${{ env.BUILD_PROFILE }}
        key: ${{ runner.os }}-cargo-${{ env.BUILD_PROFILE }}-${{ hashFiles('rust-toolchain.toml', '**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ env.BUILD_PROFILE }}-
    - name: Cache sccache directory
      if: ${{ inputs.use-sccache == 'true' && github.event_name != 'release' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/sccache
        key: ${{ runner.os }}-sccache-${{ env.BUILD_PROFILE }}-${{ hashFiles('rust-toolchain.toml', '**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-sccache-${{ env.BUILD_PROFILE }}-
    - name: Run sccache on non-release runs
      if: ${{ inputs.use-sccache == 'true' && github.event_name != 'release' }}
      uses: mozilla-actions/sccache-action@${{ inputs.sccache-action-version }}
    - name: Set Rust caching env vars only on non-release runs
      if: ${{ inputs.use-sccache == 'true' && github.event_name != 'release' }}
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
    - name: Install system dependencies
      if: ${{ inputs.install-postgres-deps == 'true' && runner.os == 'Linux' }}
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libpq-dev
      shell: bash
    - name: Install libpq (headers + import library)
      if: ${{ inputs.install-postgres-deps == 'true' && runner.os == 'Windows' }}
      shell: pwsh
      run: |
        # Install PostgreSQL 17 but suppress the server service – we only need the client bits
        choco install postgresql17 --no-progress -y --params '/Password:postgres /NoService /SkipStackBuilder'

        # Tell the rest of the job where the headers and import library are
        $pgRoot = "${Env:ProgramFiles}\PostgreSQL\17"
        "PG_INCLUDE=$pgRoot\include" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        "PG_LIB=$pgRoot\lib"         | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "$pgRoot\bin"           | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install MSYS2 toolchain and SQLite
      if: ${{ inputs.install-sqlite-deps == 'true' && runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-sqlite3
