name: Rust Build Release
description: Build Rust project in release mode for a given target
inputs:
  target:
    description: Target triple to build
    default: x86_64-unknown-linux-gnu
  project-dir:
    description: Path to the Rust project to build
    required: false
    default: .
runs:
  using: composite
  steps:
    - name: Setup uv
      # v6.6.1
      uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6
    - name: Validate target
      shell: bash
      run: |
        set -euo pipefail
        uv run --script "$GITHUB_ACTION_PATH/src/action_setup.py" \
          validate "${{ inputs.target }}"
    - name: Determine toolchain
      shell: bash
      run: |
        set -euo pipefail
        TOOLCHAIN="$(uv run --script "$GITHUB_ACTION_PATH/src/action_setup.py" \
          toolchain \
          --target "${{ inputs.target }}" \
          --runner-os "${{ runner.os }}" \
          --runner-arch "${{ runner.arch }}")"
        echo "RBR_TOOLCHAIN=$TOOLCHAIN" >> "$GITHUB_ENV"
    - name: Setup Rust toolchain
      uses: leynos/shared-actions/.github/actions/setup-rust@f9f1c863c8a5bef64aa6779caa746e1a4a6c1ad4
      with:
        toolchain: ${{ env.RBR_TOOLCHAIN }}
    - name: Build release
      shell: bash
      env:
        RBR_TARGET: ${{ inputs.target }}
        RBR_TOOLCHAIN: ${{ env.RBR_TOOLCHAIN }}
      run: |
        set -euo pipefail
        cd "${{ inputs.project-dir }}"
        uv run --script "$GITHUB_ACTION_PATH/src/main.py"
