name: Rust Build Release
description: Build Rust project in release mode for a given target
inputs:
  target:
    description: Target triple to build
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Run build script
      shell: bash
      env:
        RBR_TARGET: ${{ inputs.target }}
      run: RBR_TARGET="${RBR_TARGET}" "${{ github.action_path }}/src/main.sh"
