name: Rust Build Release
description: Build Rust project in release mode for a given target
inputs:
  target:
    description: Target triple to build
    required: true
    default: x86_64-unknown-linux-gnu
  project-dir:
    description: Path to the Rust project to build
    required: false
    default: .
runs:
  using: composite
  steps:
    - name: Setup Rust toolchain
      uses: leynos/shared-actions/.github/actions/setup-rust@97de6bf6e4d4b83bf58b5c039378a33c7dc0a1be
      with:
        toolchain: 1.89.0
    - name: Build release
      shell: bash
      env:
        RBR_TARGET: ${{ inputs.target }}
        RBR_TOOLCHAIN: 1.89.0
      working-directory: ${{ inputs.project-dir }}
      run: ${{ github.action_path }}/src/main.py
