name: Rust Build Release
description: Build Rust project in release mode for a given target
inputs:
  target:
    description: Target triple to build
    required: false
runs:
  using: composite
  steps:
    - name: Run build script
      shell: bash
      run: ${{ github.action_path }}/src/main.sh "${{ inputs.target }}"
