name: Windows package
description: Build a WiX v4 MSI from prebuilt application assets on Windows runners
inputs:
  wxs-path:
    description: Path to a custom WiX authoring (.wxs) file. When omitted the action renders a default template.
    required: false
    default: ''
  application-path:
    description: >-
      Source executable or bundle that should be installed. When combined with `|relative\\path` the
      portion after the pipe customises the install location beneath the install directory.
    required: false
    default: ''
  additional-files:
    description: >-
      Additional file specifications in the form `source|relative\\path`. Provide one per line to install
      supporting assets alongside the main application.
    required: false
    default: ''
  product-name:
    description: Display name used by the generated WiX authoring when `wxs-path` is omitted.
    required: false
    default: ''
  manufacturer:
    description: Manufacturer string embedded in the generated template when `wxs-path` is omitted.
    required: false
    default: ''
  install-dir-name:
    description: Directory name created beneath Program Files for the default template.
    required: false
    default: ''
  description:
    description: Optional installer description stored in the MSI summary information stream.
    required: false
    default: ''
  upgrade-code:
    description: Stable UpgradeCode GUID for the generated MSI. Defaults to a deterministic value when omitted.
    required: false
    default: ''
  architecture:
    description: Target architecture passed to `wix build` (for example `x64` or `x86`).
    required: false
    default: x64
  version:
    description: >
      Version string to embed in the MSI. If omitted the action strips a leading
      `v` from `GITHUB_REF_NAME` and falls back to `0.0.0` when no tag is
      available.
    required: false
  dotnet-version:
    description: The .NET SDK version installed before invoking the WiX CLI.
    required: false
    default: 8.0.x
  wix-tool-version:
    description: Optional version constraint for the `wix` .NET global tool.
    required: false
  wix-extension:
    description: WiX extension to install and load during the build.
    required: false
    default: WixToolset.UI.wixext
  wix-extension-version:
    description: Version of the WiX extension to install via `wix extension add`.
    required: false
    default: '4'
  output-basename:
    description: Base filename for the generated MSI without extension.
    required: false
    default: MyApp
  output-directory:
    description: Directory where the MSI will be written.
    required: false
    default: out
  license-plaintext-path:
    description: Optional UTF-8 plain text license file converted to RTF before building.
    required: false
    default: ''
  license-rtf-path:
    description: Destination path for the generated license RTF when converting from plain text.
    required: false
    default: ''
  upload-artefact:
    description: Upload the generated MSI with `actions/upload-artifact`.
    required: false
    default: 'true'
  artefact-name:
    description: Artefact name when `upload-artefact` is enabled.
    required: false
    default: msi
outputs:
  version:
    description: Version string resolved for the MSI build.
    value: ${{ steps.resolve-version.outputs.version }}
  msi-path:
    description: Absolute path to the generated MSI file.
    value: ${{ steps.build-msi.outputs.msi-path }}
runs:
  using: composite
  steps:
    - name: Ensure Windows runner
      shell: pwsh
      run: |
        & "${{ github.action_path }}\scripts\ensure_windows_runner.ps1"
    - name: Validate inputs
      shell: pwsh
      env:
        WXS_PATH: ${{ inputs.wxs-path }}
        APPLICATION_SPEC: ${{ inputs.application-path }}
      run: |
        & "${{ github.action_path }}\scripts\validate_inputs.ps1"
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      shell: pwsh
      run: |
        python -m pip install --disable-pip-version-check "cyclopts>=3.24,<4" "jinja2>=3.1,<4"
    - name: Install WiX CLI and extensions
      shell: pwsh
      env:
        WIX_TOOL_VERSION: ${{ inputs.wix-tool-version }}
        WIX_EXTENSION: ${{ inputs.wix-extension }}
        WIX_EXTENSION_VERSION: ${{ inputs.wix-extension-version }}
      run: |
        & "${{ github.action_path }}\scripts\install_wix_cli.ps1"
    - id: resolve-version
      name: Resolve package version
      shell: pwsh
      env:
        INPUT_VERSION: ${{ inputs.version }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
      run: |
        & "${{ github.action_path }}\scripts\resolve_version.ps1"
    - id: build-msi
      name: Build MSI
      shell: pwsh
      env:
        WXS_PATH: ${{ inputs.wxs-path }}
        APPLICATION_SPEC: ${{ inputs.application-path }}
        ADDITIONAL_FILES: ${{ inputs.additional-files }}
        PRODUCT_NAME: ${{ inputs.product-name }}
        MANUFACTURER: ${{ inputs.manufacturer }}
        INSTALL_DIR_NAME: ${{ inputs.install-dir-name }}
        DESCRIPTION: ${{ inputs.description }}
        UPGRADE_CODE: ${{ inputs.upgrade-code }}
        ARCHITECTURE: ${{ inputs.architecture }}
        OUTPUT_BASENAME: ${{ inputs.output-basename }}
        OUTPUT_DIRECTORY: ${{ inputs.output-directory }}
        VERSION: ${{ steps.resolve-version.outputs.version }}
        WIX_EXTENSION: ${{ inputs.wix-extension }}
        LICENSE_TEXT_PATH: ${{ inputs.license-plaintext-path }}
        LICENSE_RTF_PATH: ${{ inputs.license-rtf-path }}
      run: |
        & "${{ github.action_path }}\scripts\build_msi.ps1"
    - name: Upload MSI artefact
      if: ${{ fromJSON(inputs.upload-artefact) }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artefact-name }}
        path: ${{ steps.build-msi.outputs.msi-path }}
branding:
  icon: package
  color: blue
