project_name: rust-toy-app
version: 2
dist: dist
builds:
  - id: prebuilt-amd64
    main: ./does-not-exist.go
    binary: rust-toy-app
    skip: true
    goos: linux
    goarch: amd64
  - id: prebuilt-arm64
    main: ./does-not-exist.go
    binary: rust-toy-app
    skip: true
    goos: linux
    goarch: arm64
nfpms:
  - id: deb
    builds:
      - prebuilt-amd64
      - prebuilt-arm64
    package_name: rust-toy-app
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    maintainer: "Example <ops@example.com>"
    homepage: "https://example.com"
    description: "Toy application for release pipeline tests"
    license: "MIT"
    formats:
      - deb
    contents:
      - src: dist/rust-toy-app_linux_{{ .Arch }}/rust-toy-app
        dst: /usr/bin/rust-toy-app
        type: file
      - src: dist/rust-toy-app_linux_{{ .Arch }}/rust-toy-app.1
        dst: /usr/share/man/man1/rust-toy-app.1
        type: file
