# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
project_name: rust-toy-app
version: 2
dist: dist
builds:
  - id: prebuilt
    builder: rust
    binary: rust-toy-app
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    skip: true
    dir: "dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
nfpms:
  - id: deb
    builds:
      - prebuilt
    package_name: rust-toy-app
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    maintainer: "Example <ops@example.com>"
    homepage: "https://example.com"
    description: "Toy application for release pipeline tests"
    license: "MIT"
    formats:
      - deb
    contents:
      - src: dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/{{ .Binary }}
        dst: /usr/bin/{{ .Binary }}
        type: file
      - src: dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/{{ .Binary }}.1
        dst: /usr/share/man/man1/{{ .Binary }}.1
        type: file
