name: Generate coverage
description: Run test coverage for Rust, Python and mixed Rust and Python projects
inputs:
  features:
    description: Cargo features to enable
    required: false
  with-default-features:
    description: Enable default features
    required: false
    default: "true"
  use-cargo-nextest:
    description: Use cargo-nextest for Rust coverage runs
    required: false
    default: "true"
  output-path:
    description: Output file path
    required: true
  format:
    description: Coverage format
    required: false
    default: cobertura
  with-ratchet:
    description: Fail if coverage falls below the stored baseline
    required: false
    default: "false"
  artefact-name-suffix:
    description: Optional suffix appended to the coverage artefact name
    required: false
  baseline-rust-file:
    description: Path to store the Rust coverage baseline
    required: false
    default: .coverage-baseline.rust
  baseline-python-file:
    description: Path to store the Python coverage baseline
    required: false
    default: .coverage-baseline.python
  with-cucumber-rs:
    description: Run cucumber-rs scenarios under coverage
    required: false
    default: "false"
  cucumber-rs-features:
    description: Path to cucumber feature files
    required: false
  cucumber-rs-args:
    description: Extra arguments for cucumber
    required: false
outputs:
  file:
    description: Path to the generated coverage file
    value: ${{ steps.out.outputs.file }}
  format:
    description: Format of the coverage file
    value: ${{ steps.out.outputs.format }}
  lang:
    description: Detected project language
    value: ${{ steps.detect.outputs.lang }}
  artefact-name:
    description: Name used for the uploaded coverage artefact
    value: ${{ steps.out.outputs.artefact_name }}
runs:
  using: composite
  steps:
    - name: Setup uv
      # v6.4.3
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc
      with:
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
        cache-suffix: action-${{ github.action_ref || github.sha }}
    - id: detect
      run: uv run --script "${{ github.action_path }}/scripts/detect.py"
      env:
        INPUT_FORMAT: ${{ inputs.format }}
      shell: bash
    - name: Restore baselines
      id: restore-baselines
      if: inputs.with-ratchet == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.baseline-rust-file }}
          ${{ inputs.baseline-python-file }}
        key: ratchet-baseline-${{ runner.os }}-${{ github.run_id }}
        restore-keys: ratchet-baseline-${{ runner.os }}-
    - name: Ensure baseline files
      if: inputs.with-ratchet == 'true'
      run: |
        if [ ! -f "${{ inputs.baseline-rust-file }}" ]; then
          mkdir -p "$(dirname '${{ inputs.baseline-rust-file }}')"
          echo 0 > "${{ inputs.baseline-rust-file }}"
        fi
        if [ ! -f "${{ inputs.baseline-python-file }}" ]; then
          mkdir -p "$(dirname '${{ inputs.baseline-python-file }}')"
          echo 0 > "${{ inputs.baseline-python-file }}"
        fi
      shell: bash
    - name: Cache cargo artefacts
      if: steps.detect.outputs.lang == 'rust' || steps.detect.outputs.lang == 'mixed'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-llvm-cov
          ~/.cargo/bin/cargo-nextest
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-llvmcov-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-llvmcov-
    - name: Install cargo-llvm-cov
      if: steps.detect.outputs.lang == 'rust' || steps.detect.outputs.lang == 'mixed'
      run: uv run --script "${{ github.action_path }}/scripts/install_cargo_llvm_cov.py"
      shell: bash
    - name: Install cargo-binstall
      if: (steps.detect.outputs.lang == 'rust' || steps.detect.outputs.lang == 'mixed') && inputs.use-cargo-nextest == 'true'
      run: |
        set -euo pipefail
        # Keep BINSTALL_VERSION and BINSTALL_SHA256 in sync; update both together.
        # To refresh the checksum: curl -fsSL "$INSTALLER_URL" | shasum -a 256 | awk '{print $1}'
        BINSTALL_VERSION="v1.16.6"
        BINSTALL_SHA256="c2e963fbab3bdd8653b59c28d349bf85740cf4998e5e398d250dcd2884cd667d"
        INSTALLER_URL="https://raw.githubusercontent.com/cargo-bins/cargo-binstall/${BINSTALL_VERSION}/install-from-binstall-release.sh"
        INSTALLER_PATH="$(mktemp)"
        trap 'rm -f "$INSTALLER_PATH"' EXIT
        curl -fsSL --proto '=https' --tlsv1.2 "$INSTALLER_URL" -o "$INSTALLER_PATH"
        if [ ! -s "$INSTALLER_PATH" ]; then
          echo "cargo-binstall installer download failed or empty" >&2
          exit 1
        fi
        if command -v sha256sum >/dev/null 2>&1; then
          ACTUAL_SHA256="$(sha256sum "$INSTALLER_PATH" | awk '{print $1}')"
        else
          ACTUAL_SHA256="$(shasum -a 256 "$INSTALLER_PATH" | awk '{print $1}')"
        fi
        if [ "$ACTUAL_SHA256" != "$BINSTALL_SHA256" ]; then
          echo "cargo-binstall install script checksum mismatch: $ACTUAL_SHA256" >&2
          exit 1
        fi
        bash "$INSTALLER_PATH"
      shell: bash
    - name: Install cargo-nextest
      if: (steps.detect.outputs.lang == 'rust' || steps.detect.outputs.lang == 'mixed') && inputs.use-cargo-nextest == 'true'
      run: uv run --script "${{ github.action_path }}/scripts/install_cargo_nextest.py"
      shell: bash
    # This isn't how you install cucumber :'(
    #- name: Install cargo-cucumber
    #  if: inputs.with-cucumber-rs == 'true' && (steps.detect.outputs.lang == 'rust' || steps.detect.outputs.lang == 'mixed')
    #  run: cargo install cargo-cucumber --force
    #  shell: bash
    - id: rust
      if: steps.detect.outputs.lang == 'rust' || steps.detect.outputs.lang == 'mixed'
      run: uv run --script "${{ github.action_path }}/scripts/run_rust.py"
      env:
        DETECTED_LANG: ${{ steps.detect.outputs.lang }}
        DETECTED_FMT: ${{ steps.detect.outputs.fmt }}
        INPUT_OUTPUT_PATH: ${{ inputs.output-path }}
        INPUT_FEATURES: ${{ inputs.features }}
        INPUT_WITH_DEFAULT_FEATURES: ${{ inputs.with-default-features }}
        INPUT_USE_CARGO_NEXTEST: ${{ inputs.use-cargo-nextest }}
        INPUT_WITH_CUCUMBER_RS: ${{ inputs.with-cucumber-rs }}
        INPUT_CUCUMBER_RS_FEATURES: ${{ inputs.cucumber-rs-features }}
        INPUT_CUCUMBER_RS_ARGS: ${{ inputs.cucumber-rs-args }}
        BASELINE_RUST_FILE: ${{ inputs.baseline-rust-file }}
      shell: bash

    - name: Cache Python deps
      if: steps.detect.outputs.lang == 'python' || steps.detect.outputs.lang == 'mixed'
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-py-deps-${{ hashfiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-py-deps-

    - id: python
      if: steps.detect.outputs.lang == 'python' || steps.detect.outputs.lang == 'mixed'
      run: uv run --script "${{ github.action_path }}/scripts/run_python.py"
      env:
        DETECTED_LANG: ${{ steps.detect.outputs.lang }}
        DETECTED_FMT: ${{ steps.detect.outputs.fmt }}
        INPUT_OUTPUT_PATH: ${{ inputs.output-path }}
        BASELINE_PYTHON_FILE: ${{ inputs.baseline-python-file }}
      shell: bash
    - if: steps.detect.outputs.lang == 'mixed'
      run: uv run --script "${{ github.action_path }}/scripts/merge_cobertura.py"
      env:
        RUST_FILE: ${{ steps.rust.outputs.file }}
        PYTHON_FILE: ${{ steps.python.outputs.file }}
        OUTPUT_PATH: ${{ inputs.output-path }}
      shell: bash
    - name: Ratchet coverage
      if: inputs.with-ratchet == 'true'
      run: |
        set -euo pipefail
        ratchet() {
          uv run --script "${{ github.action_path }}/scripts/ratchet_coverage.py" \
            --baseline-file "$1" \
            --current "$2"
        }

        lang="${{ steps.detect.outputs.lang }}"
        if [[ "$lang" == "rust" || "$lang" == "mixed" ]]; then
          ratchet "${{ inputs.baseline-rust-file }}" "${{ steps.rust.outputs.percent }}"
        fi
        if [[ "$lang" == "python" || "$lang" == "mixed" ]]; then
          ratchet "${{ inputs.baseline-python-file }}" "${{ steps.python.outputs.percent }}"
        fi
      shell: bash
    - name: Save baselines
      if: success() && inputs.with-ratchet == 'true' && steps.restore-baselines.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.baseline-rust-file }}
          ${{ inputs.baseline-python-file }}
        key: ratchet-baseline-${{ runner.os }}

    - id: out
      run: uv run --script "${{ github.action_path }}/scripts/set_outputs.py"
      env:
        DETECTED_FMT: ${{ steps.detect.outputs.fmt }}
        INPUT_OUTPUT_PATH: ${{ inputs.output-path }}
        INPUT_ARTEFACT_NAME_SUFFIX: ${{ inputs.artefact-name-suffix }}
        GITHUB_JOB: ${{ github.job }}
        STRATEGY_JOB_INDEX: ${{ strategy.job-index }}
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
      shell: bash
    - name: Archive coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.out.outputs.artefact_name }}
        # Fallback to the configured output path when the step that sets
        # outputs didn't run successfully and the file output is empty.
        path: ${{ steps.out.outputs.file || inputs.output-path }}
        retention-days: 14
